version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  ignore:
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: eslint
    versions:
    - 7.22.0
